config/routes.rb
Rails.application.routes.draw do

  root "users/posts#top"
  get "about" => "users/posts#about"

  devise_for :stores, controllers: {
    sessions: "stores/sessions",
    passwords: "stores/passwords",
    registrations: "stores/registrations",
  }

  namespace :stores do
    #resources :sends, except: [:destroy] 予約語を使用していたためpostを新しく制作
    resources :posts, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :areas, only: [:index, :create, :edit, :update]
    resources :infomations, only: [:new, :create, :edit, :show, :update, :destroy]
    delete "posts/:id/delete" => "posts#delete"
  end

  scope module: :stores do
    get "stores/mypage" => "stores#show"
    get "stores/information/edit" => "stores#edit", as: "store_edit_information"
    patch "stores/information" => "stores#update", as: "store_update_information"
    put "stores/information" => "stores#update"
    get "stores/unsubscribe" => "stores#unsubscribe", as: "store_confirm_unsubscribe"
    delete "stores/destroy_all" => "stores#destroy_all", as: "destroy_all_store"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  namespace :users do
    resources :stores, only: [:index, :show] do
         resources :relationships, only: [:create, :destroy]
       end
    get "users/:id/relationships" => "users#relationships", as: "store_follow"
    get "users/:id/timeline" => "users#timeline", as: "store_timeline"
    get "users/relationship_ranking" => "stores#relationship_ranking", as: "store_ranking"
    get "users/:area_id/area_ranking" => "stores#area_ranking", as: "area_ranking"
    #resources :sends, only: [:index, :show]　上記と同じ
    resources :posts, only: [:index, :show]
    resources :users, only: [:index]

  end

  scope module: :users do
    get "users/mypage" => "users#show"
    get "users/information/edit" => "users#edit", as: "user_edit_information"
    patch "users/information" => "users#update", as: "user_update_information"
    put "users/information" => "users#update"
    get "users/unsubscribe" => "users#unsubscribe", as: "user_confirm_unsubscribe"
    delete "users/leave" => "users#leave", as: "leave_user"

  end

  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }

  namespace :admins do
    resources :stores, only: [:index, :show]
    resources :users, only: [:index, :show, :destroy]
    delete "stores/:id/destroy_all" => "stores#destroy_all"
    resources :areas
  end

end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :infomations, dependent: :destroy
  has_many :posts, dependent: :delete_all

  has_many :relationships, dependent: :destroy
  belongs_to :area

  attachment :store_image

  validates :corporation_name, presence: true
  validates :store_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def relationshiped_by?(user)
    relationships.where(user_id: user.id).exists?
  end
end

app/controllers/admins/stores_controller.rb
class Admins::StoresController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@stores = Store.all
  end

  def show
  	@store = Store.find(params[:id])
  end

  def destroy_all
    @store = Store.find_by(id: params[:id])
    @store.destroy
      redirect_to admins_stores_path, notice: '店舗を削除しました'
  end

  private
  def store_params
    params.require(:store).permit(:corporation_name, :store_name, :email, :postal_code, :address, :telephone_number, :store_image, :area_id)
  end
end

app/controllers/stores/confirmations_controller.rb
# frozen_string_literal: true

class Stores::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/stores/infomations_controller.rb
class Stores::InfomationsController < ApplicationController
  before_action :authenticate_store!
  before_action :ensure_correct_store, only: [:edit, :update, :destroy]

  def new
    @infomation = Infomation.new
  end

  def show
    @infomation = Infomation.find(params[:id])
    @store = @infomation.store
  end

  def create
    @infomation = Infomation.new(infomation_params)
    @infomation.store_id = current_store.id

    if @infomation.save
      redirect_to stores_posts_path(@post)
    else
      render "new"
    end
  end

  def edit
    @infomation = Infomation.find(params[:id])
  end

  def update
    @infomation = Infomation.find(params[:id])
    if @infomation.update(infomation_params)
      redirect_to stores_posts_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @infomation = Infomation.find_by(id: params[:id])
    @infomation.destroy
      redirect_to stores_posts_path(@post)
  end

  private

  def infomation_params
    params.require(:infomation).permit(:introduction, :info_image, :store_id, :titles)
  end

  def ensure_correct_store
    @infomation = Infomation.find(params[:id])
    if current_store != @infomation.store
      redirect_to stores_posts_path
    end
  end
end

app/controllers/stores/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Stores::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/stores/passwords_controller.rb
# frozen_string_literal: true

class Stores::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stores/posts_controller.rb
class Stores::PostsController < ApplicationController
  before_action :authenticate_store!
  before_action :ensure_correct_store, only:[:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def index
    @store = current_store
    @posts = @store.posts.order(created_at: :desc).page(params[:page]).per(10)
    @infomations = @store.infomations
  end

  def show
    @post = Post.find(params[:id])
    @store = @post.store
  end

  def create
    @post = Post.new(post_params)
    @post.store_id = current_store.id
    if @post.save
        tag_list = Vision.get_image_data(@post.send_image)
        tag_list.each do |tag|
          @post.tags.create(name: tag)
        end
        redirect_to stores_posts_path(@post)
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
        tag_list = Vision.get_image_data(@post.send_image)
        tag_list.each do |tag|
          @post.tags.update(name: tag)
        end
        redirect_to stores_posts_path(@post)
    else
      render "edit"
    end
  end

  def delete
    @post = Post.find_by(id: params[:id])
    @post.delete
      redirect_to stores_posts_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:send_comment, :send_image, :store_id, :title)
  end

  def ensure_correct_store
    @post = Post.find(params[:id])
    if current_store != @post.store
      redirect_to stores_posts_path
    end
  end
end

app/controllers/stores/registrations_controller.rb
# frozen_string_literal: true

class Stores::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:corporation_name, :store_name, :postal_code, :address, :telephone_number, :area_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    stores_mypage_path
  end

  def after_update_path_for(resource)
    stores_mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores/sessions_controller.rb
# frozen_string_literal: true

class Stores::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    stores_posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/stores/stores_controller.rb
class Stores::StoresController < ApplicationController
  before_action :authenticate_store!
  before_action :set_current_store


  def show
  end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to stores_mypage_path
    else
      render :edit
    end
  end

  def destroy_all
    @store.destroy
    redirect_to root_path, notice: "ご利用、ありがとうございました。"
  end

  def unsubscribe

  end

  private

  def set_current_store
    @store = current_store
  end

  def store_params
    params.require(:store).permit(:corporation_name, :store_name, :email, :postal_code, :address, :telephone_number, :store_introduction, :store_image, :area_id, :latitude, :longitude)
  end

end

app/controllers/stores/unlocks_controller.rb
# frozen_string_literal: true

class Stores::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/stores_controller.rb
class Users::StoresController < ApplicationController
  before_action :authenticate_user!

  def index
    @areas = Area.where(is_active: true)

    if params[:area_id]
      @area = Area.find(params[:area_id])
      @stores = @area.stores.order("corporation_name").page(params[:page])
      @stores_count = @area.stores.count
    else
      @stores = Store.all.order("corporation_name").page(params[:page])
      @stores_count = Store.count
    end
  end

  def show
    @user = current_user
    @store = Store.find(params[:id])
    @posts = @store.posts.order(created_at: :desc).page(params[:page]).per(10)
    @infomations = @store.infomations
  end

  def relationship_ranking
    @all_ranks = Store.find(Relationship.group(:store_id).order('count(store_id) desc').limit(10).pluck(:store_id))
  end

  def area_ranking
    @areas = Area.where(is_active: true)
  if params[:area_id]
    @area = Area.find(params[:area_id])
  end
    @all_ranks = Store.find(Relationship.group(:store_id).order('count(store_id) desc').limit(10).pluck(:store_id))
    @area_ranks = @all_ranks.select{ |store| store.area_id == @area.id }
  end
end

app/helpers/admins/stores_helper.rb
module Admins::StoresHelper
end

app/helpers/stores/areas_helper.rb
module Stores::AreasHelper
end

app/helpers/stores/genre_relationships_helper.rb
module Stores::GenreRelationshipsHelper
end

app/helpers/stores/genres_helper.rb
module Stores::GenresHelper
end

app/helpers/stores/infomations_helper.rb
module Stores::InfomationsHelper
end

app/helpers/stores/posts_helper.rb
module Stores::PostsHelper
end

app/helpers/stores/sends_helper.rb
module Stores::SendsHelper
end

app/helpers/stores/stores_helper.rb
module Stores::StoresHelper
end

app/views/stores/stores/edit.html.erb
<div class="container store-edit">
	<div class="row">
		<h2>店舗情報編集</h2>

		<%= form_for(@store, url: store_update_information_path) do |f| %>

			<div class="store-edit-image">
				<%= f.label :store_image, "アカウント画像" %>
				<div class="store-edit-image2">
				<%= attachment_image_tag @store, :store_image, format: "jpeg", size: "100x100", fallback: asset_path("no-image.jpeg"), id: "img_prev", size: '100x100' %>
				</div>
				<%= f.attachment_field :store_image %>
			</div>

		<table class="table table-hover">
			<div class ="col-xs-6">

			<tbody>

				<tr>
					<td><%= f.label :corporation_name, "会社名" %></td>
					<td><%= f.text_field :corporation_name, :placeholder =>"#{@store.corporation_name}", :size=>"40" %></td>
				</tr>

				<tr>
					<td><%= f.label :store_name, "店舗名" %></td>
					<td><%= f.text_field :store_name, :placeholder =>"#{@store.store_name}", :size=>"40" %></td>
				</tr>

				<tr>
					<td><%= f.label :postal_code, "郵便番号(ハイフンなし7桁)" %></td>
					<td><%= f.text_field :postal_code, :placeholder =>"#{@store.postal_code}", :size=>"40" %></td>
				</tr>

				<tr>
					<td><%= f.label :address, "住所" %></td>
					<td><%= f.text_field :address, :placeholder =>"#{@store.address}", :size=>"40" %></td>
				</tr>

				<tr>
					<td><%= f.label :telephone_number, "電話番号" %></td>
					<td><%= f.text_field :telephone_number, :placeholder =>"#{@store.telephone_number}", :size=>"40" %></td>
				</tr>

				<tr>
					<td><%= f.label :email, "メールアドレス" %></td>
					<td><%= f.email_field :email, autocomplete: "email", :placeholder =>"#{@store.email}", :size=>"40" %></td>
				</tr>

				<tr>
					<td><%= f.label :store_introduction, "店舗紹介" %></td>
					<td><%= f.text_area :store_introduction, :placeholder =>"#{@store.store_introduction}", :size=>"80x5" %></td>
				</tr>

				<tr>
					<td><%= f.label :store_area, "店舗地域タグ" %></td>
					<td><%= f.collection_select :area_id, Area.all, :id, :area_name, :placeholder =>"#{@store.area}"  %></td>
				</tr>

				<tr>
					<td><%= f.submit "編集内容を保存する", class: "btn btn-primary" %></td>
					<td><%= link_to "退会する", store_confirm_unsubscribe_path, class: "btn btn-danger" %></td>
				</tr>
			</tbody>
			</div>
		</table>
		<% end %>

		<script>
          $(function(){
            $('#store_store_image').on('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
              $(".store_image").attr('src', e.target.result);
            }
            reader.readAsDataURL(e.target.files[0]);
          });
          });
        </script>
	</div>
</div>

app/views/stores/stores/show.html.erb
<div class="container store-show">
	<div class="row">
		<h1>店舗詳細ページ</h1>
		<div class="store-show-btn">
		<%= link_to "編集する", store_edit_information_path, class: "btn btn-success" %>
		<%= link_to "パスワードを変更する", edit_store_registration_path, class: "btn btn-success" %>
	</div>

		<div class="store-show-image">
			<p>アカウント画像</p><%= attachment_image_tag @store, :store_image, format: "jpeg", size: "100x100", fallback: asset_path("no-image.jpeg"), size:'100x100' %>
		</div>

		<table class="table table-hover">
			<div class ="col-lg-6">

			<tbody>
				<tr><th>会社名</th><td><%= @store.corporation_name %></td></tr>
				<tr><th>店舗名</th><td><%= @store.store_name %></td></tr>
				<tr><th>郵便番号</th><td><%= @store.postal_code %></td></tr>
				<tr><th>住所</th><td><%= @store.address %></td></tr>
				<tr><th>電話番号</th><td><%= @store.telephone_number %></td></tr>
				<tr><th>メールアドレス</th><td><%= @store.email%></td></tr>
				<tr><th>店舗紹介</th><td><%= @store.store_introduction %></td></tr>
			</tbody>
		</table>
	</div>
</div>

app/views/stores/stores/unsubscribe.html.erb
<div class="container store-unsubscribe">
	<div class="row">

		<h2>本当に退会しますか？</h2>
		<h3>退会する場合は、「退会する」をクリックしてください。</h3>
		<%= link_to "マイページに戻る", stores_mypage_path, class: "btn btn-primary" %>
		<%= link_to "退会する", destroy_all_store_path, method: :delete, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: "btn btn-danger" %>

	</div>
</div>