config/routes.rb
Rails.application.routes.draw do

  root "users/posts#top"
  get "about" => "users/posts#about"

  devise_for :stores, controllers: {
    sessions: "stores/sessions",
    passwords: "stores/passwords",
    registrations: "stores/registrations",
  }

  namespace :stores do
    #resources :sends, except: [:destroy] 予約語を使用していたためpostを新しく制作
    resources :posts, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :areas, only: [:index, :create, :edit, :update]
    resources :infomations, only: [:new, :create, :edit, :show, :update, :destroy]
    delete "posts/:id/delete" => "posts#delete"
  end

  scope module: :stores do
    get "stores/mypage" => "stores#show"
    get "stores/information/edit" => "stores#edit", as: "store_edit_information"
    patch "stores/information" => "stores#update", as: "store_update_information"
    put "stores/information" => "stores#update"
    get "stores/unsubscribe" => "stores#unsubscribe", as: "store_confirm_unsubscribe"
    delete "stores/destroy_all" => "stores#destroy_all", as: "destroy_all_store"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  namespace :users do
    resources :stores, only: [:index, :show] do
         resources :relationships, only: [:create, :destroy]
       end
    get "users/:id/relationships" => "users#relationships", as: "store_follow"
    get "users/:id/timeline" => "users#timeline", as: "store_timeline"
    get "users/relationship_ranking" => "stores#relationship_ranking", as: "store_ranking"
    get "users/:area_id/area_ranking" => "stores#area_ranking", as: "area_ranking"
    #resources :sends, only: [:index, :show]　上記と同じ
    resources :posts, only: [:index, :show]
    resources :users, only: [:index]

  end

  scope module: :users do
    get "users/mypage" => "users#show"
    get "users/information/edit" => "users#edit", as: "user_edit_information"
    patch "users/information" => "users#update", as: "user_update_information"
    put "users/information" => "users#update"
    get "users/unsubscribe" => "users#unsubscribe", as: "user_confirm_unsubscribe"
    delete "users/leave" => "users#leave", as: "leave_user"

  end

  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }

  namespace :admins do
    resources :stores, only: [:index, :show]
    resources :users, only: [:index, :show, :destroy]
    delete "stores/:id/destroy_all" => "stores#destroy_all"
    resources :areas
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :store
  has_many :tags, dependent: :destroy

  attachment :send_image

  validates :send_comment, presence: true
  validates :send_image, presence: true

end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :infomations, dependent: :destroy
  has_many :posts, dependent: :delete_all

  has_many :relationships, dependent: :destroy
  belongs_to :area

  attachment :store_image

  validates :corporation_name, presence: true
  validates :store_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def relationshiped_by?(user)
    relationships.where(user_id: user.id).exists?
  end
end

app/controllers/admins/stores_controller.rb
class Admins::StoresController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@stores = Store.all
  end

  def show
  	@store = Store.find(params[:id])
  end

  def destroy_all
    @store = Store.find_by(id: params[:id])
    @store.destroy
      redirect_to admins_stores_path, notice: '店舗を削除しました'
  end

  private
  def store_params
    params.require(:store).permit(:corporation_name, :store_name, :email, :postal_code, :address, :telephone_number, :store_image, :area_id)
  end
end

app/controllers/stores/confirmations_controller.rb
# frozen_string_literal: true

class Stores::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/stores/infomations_controller.rb
class Stores::InfomationsController < ApplicationController
  before_action :authenticate_store!
  before_action :ensure_correct_store, only: [:edit, :update, :destroy]

  def new
    @infomation = Infomation.new
  end

  def show
    @infomation = Infomation.find(params[:id])
    @store = @infomation.store
  end

  def create
    @infomation = Infomation.new(infomation_params)
    @infomation.store_id = current_store.id

    if @infomation.save
      redirect_to stores_posts_path(@post)
    else
      render "new"
    end
  end

  def edit
    @infomation = Infomation.find(params[:id])
  end

  def update
    @infomation = Infomation.find(params[:id])
    if @infomation.update(infomation_params)
      redirect_to stores_posts_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @infomation = Infomation.find_by(id: params[:id])
    @infomation.destroy
      redirect_to stores_posts_path(@post)
  end

  private

  def infomation_params
    params.require(:infomation).permit(:introduction, :info_image, :store_id, :titles)
  end

  def ensure_correct_store
    @infomation = Infomation.find(params[:id])
    if current_store != @infomation.store
      redirect_to stores_posts_path
    end
  end
end

app/controllers/stores/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Stores::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/stores/passwords_controller.rb
# frozen_string_literal: true

class Stores::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stores/posts_controller.rb
class Stores::PostsController < ApplicationController
  before_action :authenticate_store!
  before_action :ensure_correct_store, only:[:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def index
    @store = current_store
    @posts = @store.posts.order(created_at: :desc).page(params[:page]).per(10)
    @infomations = @store.infomations
  end

  def show
    @post = Post.find(params[:id])
    @store = @post.store
  end

  def create
    @post = Post.new(post_params)
    @post.store_id = current_store.id
    if @post.save
        tag_list = Vision.get_image_data(@post.send_image)
        tag_list.each do |tag|
          @post.tags.create(name: tag)
        end
        redirect_to stores_posts_path(@post)
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
        tag_list = Vision.get_image_data(@post.send_image)
        tag_list.each do |tag|
          @post.tags.update(name: tag)
        end
        redirect_to stores_posts_path(@post)
    else
      render "edit"
    end
  end

  def delete
    @post = Post.find_by(id: params[:id])
    @post.delete
      redirect_to stores_posts_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:send_comment, :send_image, :store_id, :title)
  end

  def ensure_correct_store
    @post = Post.find(params[:id])
    if current_store != @post.store
      redirect_to stores_posts_path
    end
  end
end

app/controllers/stores/registrations_controller.rb
# frozen_string_literal: true

class Stores::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:corporation_name, :store_name, :postal_code, :address, :telephone_number, :area_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    stores_mypage_path
  end

  def after_update_path_for(resource)
    stores_mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores/sessions_controller.rb
# frozen_string_literal: true

class Stores::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    stores_posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/stores/stores_controller.rb
class Stores::StoresController < ApplicationController
  before_action :authenticate_store!
  before_action :set_current_store


  def show
  end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to stores_mypage_path
    else
      render :edit
    end
  end

  def destroy_all
    @store.destroy
    redirect_to root_path, notice: "ご利用、ありがとうございました。"
  end

  def unsubscribe

  end

  private

  def set_current_store
    @store = current_store
  end

  def store_params
    params.require(:store).permit(:corporation_name, :store_name, :email, :postal_code, :address, :telephone_number, :store_introduction, :store_image, :area_id, :latitude, :longitude)
  end

end

app/controllers/stores/unlocks_controller.rb
# frozen_string_literal: true

class Stores::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
	def top
		@store = Store.all
  		@posts = Post.order(created_at: :desc).page(params[:page])
	end

	def about
	end
end

app/controllers/users/stores_controller.rb
class Users::StoresController < ApplicationController
  before_action :authenticate_user!

  def index
    @areas = Area.where(is_active: true)

    if params[:area_id]
      @area = Area.find(params[:area_id])
      @stores = @area.stores.order("corporation_name").page(params[:page])
      @stores_count = @area.stores.count
    else
      @stores = Store.all.order("corporation_name").page(params[:page])
      @stores_count = Store.count
    end
  end

  def show
    @user = current_user
    @store = Store.find(params[:id])
    @posts = @store.posts.order(created_at: :desc).page(params[:page]).per(10)
    @infomations = @store.infomations
  end

  def relationship_ranking
    @all_ranks = Store.find(Relationship.group(:store_id).order('count(store_id) desc').limit(10).pluck(:store_id))
  end

  def area_ranking
    @areas = Area.where(is_active: true)
  if params[:area_id]
    @area = Area.find(params[:area_id])
  end
    @all_ranks = Store.find(Relationship.group(:store_id).order('count(store_id) desc').limit(10).pluck(:store_id))
    @area_ranks = @all_ranks.select{ |store| store.area_id == @area.id }
  end
end

app/helpers/admins/stores_helper.rb
module Admins::StoresHelper
end

app/helpers/stores/areas_helper.rb
module Stores::AreasHelper
end

app/helpers/stores/genre_relationships_helper.rb
module Stores::GenreRelationshipsHelper
end

app/helpers/stores/genres_helper.rb
module Stores::GenresHelper
end

app/helpers/stores/infomations_helper.rb
module Stores::InfomationsHelper
end

app/helpers/stores/posts_helper.rb
module Stores::PostsHelper
end

app/views/stores/posts/edit.html.erb
<div class="container send-edit">
	<div class="row">

		<%= form_for(@post, url:stores_post_path) do |f| %>
			<div class="send-edit-title">
				<h3>タイムライン投稿編集ページ</h3>
			</div>

				<div class="send-edit-image">
					<h3>画像投稿</h3>
					<%= attachment_image_tag @post, :send_image, fallback: asset_path("not-image.jpeg"), id: "img_prev",style: "height: 250px; width:300px;", class: "img-responsive" %>
					<%= f.attachment_field :send_image %>
				</div>

				<div class="store_send-edit-title">
					<h3>投稿タイトル</h3>
					<%= f.text_field :title, :size=>"80" %>
				</div>

				<div class="send-edit-comment">
					<h3>投稿内容</h3>
					<%= f.text_area :send_comment, :size=>"80x5" %>
				</div>

				<div class="send-edit-submit">
					<%= f.submit "変更を保存", class: "btn btn-primary" %>
				</div>
		<% end %>

		<script>
          $(function(){
            $('#post_send_image').on('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
              $(".send_image").attr('src', e.target.result);
            }
            reader.readAsDataURL(e.target.files[0]);
          });
          });
        </script>

	</div>
</div>

app/views/stores/posts/index.html.erb
<div class="container store-index">
	<div class="row">
		<div class="col-sm-12 col-md-8">
			<div class="col-xs-12 store-index-info">
				<div class="col-xs-4">
					<div class="send-top-image">
						<%= attachment_image_tag @store, :store_image, format: "jpeg", size: "200x200", fallback: asset_path("no-image.jpeg"), size:'200x200', class: "img-responsive" %>
					</div>
				</div>

				<div class="col-xs-8 store-index-infomation">
					<h4><%= @store.corporation_name %>　<%= @store.store_name %></h4>
					<h5><%= @store.store_introduction %>
						<% if @store.store_introduction.blank? %>
							<p>店舗紹介文はマイページから編集できます。</p>
						<% end %>
					</h5>
					<p>住所<br><%= @store.address %></p>
					<p>電話番号<br><%= @store.telephone_number %></p>
               		<p>フォロワー数: <i class="fa fa-heart" aria-hidden="true" ></i><%= @store.relationships.count %></p>
				</div>
			</div>

				<div class="col-xs-12 store_send-index">
					<h3>タイムライン</h3>
						<% @posts.each do |post| %>
							<div class="store-sends">
								<div class="store_send_top">

									<%= attachment_image_tag post.store, :store_image, format: "jpeg", size: "50x50", fallback: asset_path("no-image.jpeg"), size:'50x50' %>

									<%= post.store.corporation_name %>　<%= post.store.store_name %>
								</div>

								<div class="store_send_bottom">

									<%= attachment_image_tag post, :send_image, format: "jpeg", size: "300x250", fallback: asset_path("not-image.jpeg"), size:'300x250', class: "img-responsive" %>

									<div class="store-send-bottom-insite">
										<h4><%= post.title %></h4>
										<p><%= simple_format(h(post.send_comment)) %></p>
									</div>
								</div>

									<div class ="store_send_tag">
											<% post.tags.each do |tag| %>
        										<span class="label"><%= tag.name %></span>
      										<% end %>
      									</div>
									<div class="store_send_edit">
										<%= link_to "投稿詳細", stores_post_path(post.id), class: "btn btn-primary" %>
									</div>
									<div class="store_send_create">

										<p>投稿時間:　<%= l post.created_at %></p>
									</div>
							</div>
						<% end %>
					<%= paginate @posts %>
				</div>
		</div>

		<div class="row">
			<div class="col-sm-12 col-md-4 side-bar">
				<div id="map"></div>
				<script type="text/javascript">
					function initMap() {
						var test ={lat: <%= @store.latitude %>, lng: <%= @store.longitude %>};
						var map = new google.maps.Map(document.getElementById("map"), {
							zoom: 15,
							center: test
						});
						var transitLayer = new google.maps.TransitLayer();
						transitLayer.setMap(map);
						var contentString = "住所:<%= @store.address %>";
						var infowindow = new google.maps.InfoWindow({
							content: contentString
						});
						var marker = new google.maps.Marker({
							position:test,
							map: map,
							title: contentString
						});
						marker.addListener("click", function() {
							infowindow.open(map, marker);
						});
					}
				</script>

			    <script async defer
			    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%=ENV['GOOGLE_API_KEY'] %>&callback=initMap">
				</script>

				<h3>店舗情報</h3>
					<% @infomations.each do |infomation| %>
						<div class="store-sidebar-sends">
							<h4><%= infomation.titles %></h4>
								<div class="side-bar-image">
									<%= link_to stores_infomation_path(infomation.id) do %>
                						<%= attachment_image_tag infomation, :info_image, size: "300x250", format: 'jpeg' %>
                					<% end %>
                				</div>
                				<p><%= simple_format(h(infomation.introduction)) %></p>
                				<%= link_to "投稿詳細", stores_infomation_path(infomation.id), class: "btn btn-primary" %>
                		</div>
              		<% end %>
			</div>
		</div>
	</div>
</div>

app/views/stores/posts/new.html.erb
<div class="container send-new">
	<div class="row">
    <div class="col-sm-12 col-md-8">
      <div class="send-new-title">
		    <h2>タイムライン新規投稿</h2>
      </div>

  		  <%= form_for(@post, url:stores_posts_path) do |f| %>
		      <% if @post.errors.any? %>
            <div id="error_explanation">
              <h2>error: <%= @post.errors.count %></h2>
    		        <ul>
    				      <% @post.errors.full_messages.each do |message| %>
      			       <li><%= message %></li>
    			       <% end %>
                </ul>
  		      </div>
  		    <% end %>

  		    <div class="row send-new-image">
            <h3>画像投稿</h3>
            <%= attachment_image_tag @post, :send_image, fallback: asset_path("not-image.jpeg"), id: "img_prev",style: "height: 200px; width:200px;", class: "img-responsive" %>
            <%= f.attachment_field :send_image %>
  		    </div>

          <div class="row store_send-new-title">
            <h3>投稿タイトル</h3>
            <%= f.text_field :title, :size=>"80" %>
          </div>

  		    <div class="row send-new-comment">
  		      <h3>投稿内容</h3>
  		      <%= f.text_area :send_comment, :size=>"80x5" %>
  		    </div>

  		    <div class="row send-new-submit">
  		      <%= f.submit "送信", class: "btn btn-success" %>
  		    </div>
  		  <% end %>

        <script>
          $(function(){
            $('#post_send_image').on('change', function (e) {
            var reader = new FileReader();
            reader.onload = function (e) {
              $(".send_image").attr('src', e.target.result);
            }
            reader.readAsDataURL(e.target.files[0]);
          });
          });
        </script>
    </div>

    <div class="row">
      <div class="col-sm-12 col-md-4 side-bar">
        <h3>Tips</h3>
          <p><strong>画像と投稿内容の入力は必須です。</strong></p>
          <p>タイトルは未入力でも投稿可能</p>
          <p>タイトルあり</p>
          <p><img class="sidebar-image" src="<%= asset_path "timeline1.png" %>" width="350" height="200" class="img-responsive" ></p>
          <p>タイトルなし</p>
          <p><img class="sidebar-image" src="<%= asset_path "timeline2.png" %>" width="350" height="200" class="img-responsive"></p>

      </div>
    </div>

  </div>
</div>

app/views/stores/posts/show.html.erb
<div class="container send-show">
	<div class="row">
		<div class="send-show-top">
			<%= attachment_image_tag @store, :store_image, format: "jpeg", size: "50x50", fallback: asset_path("no-image.jpeg"), size:'50x50' %>
			<%= @store.corporation_name %>　<%= @store.store_name %>
		</div>

		<div class="send-show-bottom">

			<%= attachment_image_tag @post, :send_image, format: "jpeg", size: "300x250", fallback: asset_path("not-image.jpeg"), size:'300x250', class: "img-responsive" %>


			<div class="send-show-bottom-right">
				<h4><%= @post.title %></h4>
				<p><%= simple_format(h(@post.send_comment)) %></p>
			</div>
		</div>

			<div class="show-send-date">
				<%= l @post.created_at %>
			</div>

			<div class="send-show-edit">
				<%= link_to "編集する", edit_stores_post_path(@post), class: "btn btn-primary" %>
				<%= link_to "削除する", stores_path(@post), method: :delete, class: "btn btn-danger" %>
			</div>

	</div>
</div>