config/routes.rb
Rails.application.routes.draw do

  root "users/posts#top"
  get "about" => "users/posts#about"

  devise_for :stores, controllers: {
    sessions: "stores/sessions",
    passwords: "stores/passwords",
    registrations: "stores/registrations",
  }

  namespace :stores do
    #resources :sends, except: [:destroy] 予約語を使用していたためpostを新しく制作
    resources :posts, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :areas, only: [:index, :create, :edit, :update]
    resources :infomations, only: [:new, :create, :edit, :show, :update, :destroy]
    delete "posts/:id/delete" => "posts#delete"
  end

  scope module: :stores do
    get "stores/mypage" => "stores#show"
    get "stores/information/edit" => "stores#edit", as: "store_edit_information"
    patch "stores/information" => "stores#update", as: "store_update_information"
    put "stores/information" => "stores#update"
    get "stores/unsubscribe" => "stores#unsubscribe", as: "store_confirm_unsubscribe"
    delete "stores/destroy_all" => "stores#destroy_all", as: "destroy_all_store"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  namespace :users do
    resources :stores, only: [:index, :show] do
         resources :relationships, only: [:create, :destroy]
       end
    get "users/:id/relationships" => "users#relationships", as: "store_follow"
    get "users/:id/timeline" => "users#timeline", as: "store_timeline"
    get "users/relationship_ranking" => "stores#relationship_ranking", as: "store_ranking"
    get "users/:area_id/area_ranking" => "stores#area_ranking", as: "area_ranking"
    #resources :sends, only: [:index, :show]　上記と同じ
    resources :posts, only: [:index, :show]
    resources :users, only: [:index]

  end

  scope module: :users do
    get "users/mypage" => "users#show"
    get "users/information/edit" => "users#edit", as: "user_edit_information"
    patch "users/information" => "users#update", as: "user_update_information"
    put "users/information" => "users#update"
    get "users/unsubscribe" => "users#unsubscribe", as: "user_confirm_unsubscribe"
    delete "users/leave" => "users#leave", as: "leave_user"

  end

  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }

  namespace :admins do
    resources :stores, only: [:index, :show]
    resources :users, only: [:index, :show, :destroy]
    delete "stores/:id/destroy_all" => "stores#destroy_all"
    resources :areas
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :relationships, dependent: :destroy
  has_many :relationship_stores, through: :relationships, source: :store, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :handle_name, presence: true
  validates :gender, presence: true
  validates :age, presence: true
end

app/controllers/admins/stores_controller.rb
class Admins::StoresController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@stores = Store.all
  end

  def show
  	@store = Store.find(params[:id])
  end

  def destroy_all
    @store = Store.find_by(id: params[:id])
    @store.destroy
      redirect_to admins_stores_path, notice: '店舗を削除しました'
  end

  private
  def store_params
    params.require(:store).permit(:corporation_name, :store_name, :email, :postal_code, :address, :telephone_number, :store_image, :area_id)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@users = User.all
  end

  def show
    @user = User.find(params[:id])
    @relationship_stores = @user.relationship_stores
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
      redirect_to admins_users_path, notice: '会員を削除しました'
  end

  private
  def user_params
  	params.require(:user).permit(:handle_name, :email, :gender, :age)
  end

end

app/controllers/stores/confirmations_controller.rb
# frozen_string_literal: true

class Stores::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/stores/infomations_controller.rb
class Stores::InfomationsController < ApplicationController
  before_action :authenticate_store!
  before_action :ensure_correct_store, only: [:edit, :update, :destroy]

  def new
    @infomation = Infomation.new
  end

  def show
    @infomation = Infomation.find(params[:id])
    @store = @infomation.store
  end

  def create
    @infomation = Infomation.new(infomation_params)
    @infomation.store_id = current_store.id

    if @infomation.save
      redirect_to stores_posts_path(@post)
    else
      render "new"
    end
  end

  def edit
    @infomation = Infomation.find(params[:id])
  end

  def update
    @infomation = Infomation.find(params[:id])
    if @infomation.update(infomation_params)
      redirect_to stores_posts_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @infomation = Infomation.find_by(id: params[:id])
    @infomation.destroy
      redirect_to stores_posts_path(@post)
  end

  private

  def infomation_params
    params.require(:infomation).permit(:introduction, :info_image, :store_id, :titles)
  end

  def ensure_correct_store
    @infomation = Infomation.find(params[:id])
    if current_store != @infomation.store
      redirect_to stores_posts_path
    end
  end
end

app/controllers/stores/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Stores::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/stores/passwords_controller.rb
# frozen_string_literal: true

class Stores::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stores/posts_controller.rb
class Stores::PostsController < ApplicationController
  before_action :authenticate_store!
  before_action :ensure_correct_store, only:[:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def index
    @store = current_store
    @posts = @store.posts.order(created_at: :desc).page(params[:page]).per(10)
    @infomations = @store.infomations
  end

  def show
    @post = Post.find(params[:id])
    @store = @post.store
  end

  def create
    @post = Post.new(post_params)
    @post.store_id = current_store.id
    if @post.save
        tag_list = Vision.get_image_data(@post.send_image)
        tag_list.each do |tag|
          @post.tags.create(name: tag)
        end
        redirect_to stores_posts_path(@post)
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
        tag_list = Vision.get_image_data(@post.send_image)
        tag_list.each do |tag|
          @post.tags.update(name: tag)
        end
        redirect_to stores_posts_path(@post)
    else
      render "edit"
    end
  end

  def delete
    @post = Post.find_by(id: params[:id])
    @post.delete
      redirect_to stores_posts_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:send_comment, :send_image, :store_id, :title)
  end

  def ensure_correct_store
    @post = Post.find(params[:id])
    if current_store != @post.store
      redirect_to stores_posts_path
    end
  end
end

app/controllers/stores/registrations_controller.rb
# frozen_string_literal: true

class Stores::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:corporation_name, :store_name, :postal_code, :address, :telephone_number, :area_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    stores_mypage_path
  end

  def after_update_path_for(resource)
    stores_mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores/sessions_controller.rb
# frozen_string_literal: true

class Stores::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    stores_posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/stores/stores_controller.rb
class Stores::StoresController < ApplicationController
  before_action :authenticate_store!
  before_action :set_current_store


  def show
  end

  def edit
  end

  def update
    if @store.update(store_params)
      redirect_to stores_mypage_path
    else
      render :edit
    end
  end

  def destroy_all
    @store.destroy
    redirect_to root_path, notice: "ご利用、ありがとうございました。"
  end

  def unsubscribe

  end

  private

  def set_current_store
    @store = current_store
  end

  def store_params
    params.require(:store).permit(:corporation_name, :store_name, :email, :postal_code, :address, :telephone_number, :store_introduction, :store_image, :area_id, :latitude, :longitude)
  end

end

app/controllers/stores/unlocks_controller.rb
# frozen_string_literal: true

class Stores::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @send = Send.find(params[:send_id])
    @favorite = current_user.favorites.new(send_id: @send.id)
    @favorite.save
    redirect_to request.referer
  end

  def destroy
    send = Send.find(params[:send_id])
    favorite = current_user.favorites.find_by(send_id: send.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
	def top
		@store = Store.all
  		@posts = Post.order(created_at: :desc).page(params[:page])
	end

	def about
	end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:handle_name, :email, :gender, :age])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_mypage_path
  end

  def after_update_path_for(resource)
    users_mypage_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @store = Store.find(params[:store_id])
    @relationship = current_user.relationships.new(store_id: @store.id)
    @relationship.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @store = Store.find(params[:store_id])
    @relationship = current_user.relationships.find_by(store_id: @store.id)
    @relationship.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/views/users/stores/_area.html.erb
<div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>エリア検索</th>
      </tr>
    </thead>
    <tbody>
      <% areas.each do |area| %>
        <tr>
          <td><%= link_to area.area_name, controller: "stores", area_id: area.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/stores/area_ranking.html.erb
<div class="container store-index">
	<div class="row">
		<div class="col-sm-10 col-md-8">
			<% if params[:area_id] %>
				<h3><%= @area.area_name %>フォロワーランキング</h3>
				<% end %>

			<% @area_ranks.each do |store| %>
				<div class="col-xs-12 user-store-index">
						<div class="col-xs-4 user-store-index-image">

							<%= attachment_image_tag store, :store_image, format: "jpeg", size: "150x150", fallback: asset_path("no-image.jpeg"), size:'150x150', class: "img-responsive" %>

						</div>
						<div class="col-xs-8 user-store-index-text">
							<p>会社名: 　<%= store.corporation_name %></p>
							<p>店舗名: 　<%= store.store_name %></p>
							<p>住所:　 　<%= store.address %></p>
							<p>電話番号: <%= store.telephone_number %></p>
							<p><%= link_to "店舗詳細", users_store_path(store.id), class: "btn btn-primary" %></p>
							<p>お気に入り登録者数:
							<% if store.relationshiped_by?(current_user) %>
								<%= link_to users_store_relationship_path(id: store.id, store_id: store.id), method: :delete do %>
    								<i class="fa fa-heart" aria-hidden="true" ></i>
               						<%= store.relationships.count %>
  								<% end %>
							<% else %>
  								<%= link_to users_store_relationships_path(id: store.id, store_id: store.id), method: :post do %>
   									<i class="fa fa-heart-o" aria-hidden="true"></i>
               						<%= store.relationships.count %>
  								<% end %>
							<% end %></p>

						</div>
					</div>
				<% end %>
		</div>

		<div class="row">
			<div class="col-sm-2 col-md-4">
				<table class="table table-hover">
				<tr><th>エリア別</th></tr>
				<tr><th><%= link_to "大阪市", "/users/users/1/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "豊中市", "/users/users/2/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "池田市", "/users/users/3/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "箕面市", "/users/users/4/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "能勢町", "/users/users/5/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "豊能町", "/users/users/6/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "高槻市", "/users/users/7/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "吹田市", "/users/users/8/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "茨木市", "/users/users/9/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "摂津市", "/users/users/10/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "島本町", "/users/users/11/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "堺市", "/users/users/12/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "泉大津市", "/users/users/13/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "和泉市", "/users/users/14/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "高石市", "/users/users/15/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "忠岡町", "/users/users/16/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "岸和田市", "/users/users/17/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "貝塚市", "/users/users/18/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "泉佐野市", "/users/users/19/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "泉南市", "/users/users/20/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "阪南市", "/users/users/21/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "熊取町", "/users/users/22/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "田尻町", "/users/users/23/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "岬町", "/users/users/24/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "枚方市", "/users/users/25/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "寝屋川市", "/users/users/26/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "守口市", "/users/users/27/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "大東市", "/users/users/28/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "門真市", "/users/users/29/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "四條畷市", "/users/users/30/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "交野市", "/users/users/31/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "東大阪市", "/users/users/32/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "八尾市", "/users/users/33/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "柏原市", "/users/users/34/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "富田林市", "/users/users/35/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "河内長野市", "/users/users/36/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "松原市", "/users/users/37/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "羽曳野市", "/users/users/38/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "藤井寺市", "/users/users/39/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "大阪狭山市", "/users/users/40/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "太子町市", "/users/users/41/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "河南市", "/users/users/42/area_ranking", method: :get %></th></tr>
				<tr><th><%= link_to "千早赤阪村", "/users/users/43/area_ranking", method: :get %></th></tr>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/stores/index.html.erb
<div class="container store-index">
	<div class="row">
		<div class="col-sm-10 col-md-8">
			<% if params[:area_id] %>
				<h2><%= @area.area_name %><span>(全<%= @stores_count %>件)</span></h2>
			<% else %>
				<h2>店舗一覧<spam>(全<%= @stores_count %>件)</spam></h2>
			<% end %>
				<% @stores.each do |store| %>
					<div class="col-xs-12 user-store-index">
						<div class="col-xs-4 user-store-index-image">
							<%= attachment_image_tag store, :store_image, format: "jpeg", size: "150x150", fallback: asset_path("no-image.jpeg"), size:'150x150', class: "img-responsive" %>
						</div>
						<div class="col-xs-8 user-store-index-text">
							<p>会社名: 　<%= store.corporation_name %></p>
							<p>店舗名: 　<%= store.store_name %></p>
							<p>住所:　 　<%= store.address %></p>
							<p>電話番号: <%= store.telephone_number %></p>
							<p><%= link_to "店舗詳細", users_store_path(store.id), class: "btn btn-primary" %></p>
							<p>お気に入り登録者数:
								<% if store.relationshiped_by?(current_user) %>
									<%= link_to users_store_relationship_path(id: store.id, store_id: store.id), method: :delete do %>
    									<i class="fa fa-heart" aria-hidden="true" ></i>
               							<%= store.relationships.count %>
  									<% end %>
								<% else %>
  									<%= link_to users_store_relationships_path(id: store.id, store_id: store.id), method: :post do %>
   										<i class="fa fa-heart-o" aria-hidden="true"></i>
              							<%= store.relationships.count %>
  									<% end %>
								<% end %></p>
						</div>
					</div>
				<% end %>
			<%= paginate @stores %>
		</div>

		<div class="row">
			<div class="col-sm-2 col-md-4">
				<%= render '/users/stores/area', areas: @areas %>
			</div>
		</div>
	</div>
</div>