config/routes.rb
Rails.application.routes.draw do

  root "users/posts#top"
  get "about" => "users/posts#about"

  devise_for :stores, controllers: {
    sessions: "stores/sessions",
    passwords: "stores/passwords",
    registrations: "stores/registrations",
  }

  namespace :stores do
    #resources :sends, except: [:destroy] 予約語を使用していたためpostを新しく制作
    resources :posts, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :areas, only: [:index, :create, :edit, :update]
    resources :infomations, only: [:new, :create, :edit, :show, :update, :destroy]
    delete "posts/:id/delete" => "posts#delete"
  end

  scope module: :stores do
    get "stores/mypage" => "stores#show"
    get "stores/information/edit" => "stores#edit", as: "store_edit_information"
    patch "stores/information" => "stores#update", as: "store_update_information"
    put "stores/information" => "stores#update"
    get "stores/unsubscribe" => "stores#unsubscribe", as: "store_confirm_unsubscribe"
    delete "stores/destroy_all" => "stores#destroy_all", as: "destroy_all_store"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  namespace :users do
    resources :stores, only: [:index, :show] do
         resources :relationships, only: [:create, :destroy]
       end
    get "users/:id/relationships" => "users#relationships", as: "store_follow"
    get "users/:id/timeline" => "users#timeline", as: "store_timeline"
    get "users/relationship_ranking" => "stores#relationship_ranking", as: "store_ranking"
    get "users/:area_id/area_ranking" => "stores#area_ranking", as: "area_ranking"
    #resources :sends, only: [:index, :show]　上記と同じ
    resources :posts, only: [:index, :show]
    resources :users, only: [:index]

  end

  scope module: :users do
    get "users/mypage" => "users#show"
    get "users/information/edit" => "users#edit", as: "user_edit_information"
    patch "users/information" => "users#update", as: "user_update_information"
    put "users/information" => "users#update"
    get "users/unsubscribe" => "users#unsubscribe", as: "user_confirm_unsubscribe"
    delete "users/leave" => "users#leave", as: "leave_user"

  end

  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }

  namespace :admins do
    resources :stores, only: [:index, :show]
    resources :users, only: [:index, :show, :destroy]
    delete "stores/:id/destroy_all" => "stores#destroy_all"
    resources :areas
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord

has_many :stores, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord



end

app/models/infomation.rb
class Infomation < ApplicationRecord

  belongs_to :store
  attachment :info_image

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :store
  has_many :tags, dependent: :destroy

  attachment :send_image

  validates :send_comment, presence: true
  validates :send_image, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

 	belongs_to :user
	belongs_to :store

	validates_uniqueness_of :store_id, scope: :user_id

	def relationshiped_by?(user)
    	relationships.where(user_id: user.id).exists?
  	end
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :infomations, dependent: :destroy
  has_many :posts, dependent: :delete_all

  has_many :relationships, dependent: :destroy
  belongs_to :area

  attachment :store_image

  validates :corporation_name, presence: true
  validates :store_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def relationshiped_by?(user)
    relationships.where(user_id: user.id).exists?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :relationships, dependent: :destroy
  has_many :relationship_stores, through: :relationships, source: :store, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :handle_name, presence: true
  validates :gender, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:corporation_name, :store_name, :address, :postal_code, :telephone_number, :handle_name, :age, :gender, :area_id])
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins/areas_helper.rb
module Admins::AreasHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/stores/areas_helper.rb
module Stores::AreasHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/sends_helper.rb
module Users::SendsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maketoko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/26404320e2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="style.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho" rel="stylesheet">
  </head>

  <body>

    <header class="navbar navbar-fixed-top">
      <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <%= link_to root_path do %>
          <img class="logo-image" src="<%= asset_path "logo.jpg" %>" widyh="65" height="65" >
        <% end %>
      </nav>

        <nav>

        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>

              <li class="header-link"><%= link_to "ホーム", users_store_timeline_path(current_user) %></li>

              <li class="header-link"><%= link_to "ランキング", users_store_ranking_path %></li>

              <li class="header-link"><%= link_to "店舗一覧", users_stores_path %></li>

              <li class="header-link"><%= link_to "お気に入り", users_store_follow_path(current_user) %></li>

              <li class="header-link"><%= link_to "マイページ", users_mypage_path %></li>

              <li class="header-link"><%= link_to "ログアウト",  destroy_user_session_path, method: :delete %></li>

            <% elsif store_signed_in? %>

              <li class="header-link"><%= link_to "ホーム", stores_posts_path %></li>

              <li class="header-link"><%= link_to "タイムライン投稿", new_stores_post_path %></li>

              <li class="header-link"><%= link_to "サイドバー投稿", new_stores_infomation_path %></li>

              <li class="header-link"><%= link_to "マイページ", stores_mypage_path %></li>

              <li class="header-link"><%= link_to "ログアウト", destroy_store_session_path, method: :delete %></li>

            <% elsif admin_signed_in? %>

              <li class="header-link"><%= link_to "店舗", admins_stores_path %>

              <li class="header-link"><%= link_to "会員", admins_users_path %>

              <li class="header-link"><%= link_to "エリア", admins_areas_path %>

              <li class="header-link"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>

            <% else %>

              <li class="header-link"><%= link_to "About", about_path %></li>

              <li class="header-link"><%= link_to "会員登録", new_user_registration_path %></li>

              <li class="header-link"><%= link_to "会員ログイン", new_user_session_path %></li>

              <li class="header-link"><%= link_to "店舗登録", new_store_registration_path %></li>

              <li class="header-link"><%= link_to "店舗ログイン", new_store_session_path %></li>

            <% end %>

          </ul>
        </nav>
       </div>
    </nav>
  </header>

    <%= yield %>

  <footer>
    <p class="footer">© All rights reserved by MAKETOKO.</p>
  </footer>

  </body>
</html>